#!/bin/bash

RESULTS_DIRECTORY="../results"

SYSTEM_RESOURCE_COLLECTOR="system_resource_usage_collector.sh"
DEVICE_TO_MONITOR="/dev/sda7"
SYSTEM_RESOURCE_BASE_OUTPUT_FILENAME="monitoring"

HADOOP_AWARE_COLLECTOR="hadoop_aware_collector.py"

./$SYSTEM_RESOURCE_COLLECTOR $SYSTEM_RESOURCE_BASE_OUTPUT_FILENAME $RESULTS_DIRECTORY $DEVICE_TO_MONITOR &

python $HADOOP_AWARE_COLLECTOR $RESULTS_DIRECTORY &
