#!/bin/bash

ROOT=$1

SOURCE_DIRECTORY="$1/source"
CONF_DIRECTORY="$1/conf"
RESULTS_DIRECTORY="$1/results"
LOGS_DIRECTORY="$1/logs"
MANAGEMENT_DIRECTORY="$1/management"

zip -r intrusiveness_meter.zip $SOURCE_DIRECTORY $CONF_DIRECTORY $RESULTS_DIRECTORY $LOGS_DIRECTORY $MANAGEMENT_DIRECTORY
