#
# Federal University of Campina Grande
# Distributed Systems Laboratory
#
# Author: Armstrong Mardilson da Silva Goes
# Contact: armstrongmsg@lsd.ufcg.edu.br
#

#
# This program gets a result.csv file generated by the MainAnalyser and
# produces some graphics from it.
#

library("ggplot2")

DATA_FILE_NAME <- "../result.csv"
data <- read.csv(DATA_FILE_NAME, strip.white=TRUE)
benchmarks <- subset(data, related_discomfort == "true", select = c(benchmark))

filtered_by_hadoop_cpu_usage <- subset(data, related_discomfort == "true", select = c(hadoop_cpu_usage))$hadoop_cpu_usage

for (i in 1:length(filtered_by_hadoop_cpu_usage)) {
	execution_hadoop_cpu_usage <-data.frame(as.numeric(strsplit(as.character(filtered_by_hadoop_cpu_usage[i]), " ")[[1]]))
	execution_hadoop_cpu_usage <- data.frame(execution_hadoop_cpu_usage, c(1:nrow(execution_hadoop_cpu_usage)))
	colnames(execution_hadoop_cpu_usage) <- c('X0', 'X1')

	p <- ggplot(execution_hadoop_cpu_usage, aes(execution_hadoop_cpu_usage$X1, execution_hadoop_cpu_usage$X0))
	image_name <- paste("hadoop_cpu_", i , ".png", sep="")
	png(file=image_name)
	obj <- p + geom_line() + ggtitle(sprintf("Hadoop CPU Usage: %s", benchmarks[[1]][[i]]))
	print(obj)
}
